spring.application.name=gms-backend

spring.datasource.url=jdbc:mysql://mysql:3306/gms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=demo
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

sms.viettel.api-url=https://sms.viettel.vn/api
sms.viettel.user-id=your_user_id
sms.viettel.service-id=your_service_id
sms.viettel.sender=your_sender_id
